добавляет имя наставника
htmlacademy-htmlcss/2062283-device-34 pull request #1
Opened 2022-05-17 09:06 UTC by grechah

2022-05-17 23:36 UTC, Espanol-nikkol requested changes

2022-05-17 23:36 UTC, Espanol-nikkol commented on Readme.md
> +* Наставник: [Коля Калганов](https://htmlacademy.ru/profile/id794007).
Не, ну давай без орфографических ошибок) Колганов)

2022-05-18 08:31 UTC, grechah commented on Readme.md
> +* Наставник: [Коля Калганов](https://htmlacademy.ru/profile/id794007).
виноват, исправился )

2022-05-18 15:47 UTC, Espanol-nikkol approved these changes

2022-05-18 15:48 UTC, merged