Разметил страницы
htmlacademy-htmlcss/2062283-device-34 pull request #2
Opened 2022-05-25 12:56 UTC by grechah

Разметил index.html
Создал и разметил catalog.html

2022-05-28 06:32 UTC, Espanol-nikkol requested changes

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +    <form class="search-form" action="https://echo.htmlacademy.ru/" method="get">
отступы поехали

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +    <input class="search-button" type="submit" name="submit" value="Найти">
input type="submit" - тоже самое, что и просто button

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +      <img class="login-icon" src="#" alt="Авторизация">
Суть картинки? Контентная или декоративная?

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +      <a class="navigation-link" href="#">Коля Петухов</a>
Кнопка или ссылка?

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +        <a href="#">Каталог товаров</a>
Кнопка или ссылка?)

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +          <a class="button" href="#delivery">Доставка</a>
когда ссылка ведёт в никуда, то ставим просто # в адрес

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +    <h1 class="inner-header-title">Моноподы для селфи</h1>
Отступы

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +    <header class="inner-header">
Брать один заголовок в хедер не имеет особо смысла. Либо захватывать ещё хлебные крошки, либо ограничиться одним section

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +                <input class="control-input" type="range" min="0" max="10000" step="1000" value="5000">
при отправке формы - цена не отправляется

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +            <img class="product-card-image" src="#" alt="#">
у изображений должно быть описание

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +        <button class="button pagination-show-more" type="button">ПОКАЗАТЬ ЕЩЕ</button>
Верхний регистр делается стилями, в разметке капсом писать не надо

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +      <li class="services-item">Доставка</li>
это всё ссылки

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +      <p class="contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
а зачем ещё в p оборачивать? address сам по себе тег для текста

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +          <span class="visually-hidden">Телеграм</span></a>
а зачем?

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +  <h1 class="main-title">01</h1>
не, это точно не заголовок)
Эта циферка - это декоративный элемент. Номер текущего слайда в слайдере, он не несёт информационной нагрузки

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +      <ol class="slider-pagination">
Нам здесь важен порядок?

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +  <section class="sliders">
Пожалуй, здесь всё-таки одна секция. Фоточки и описание.


![Снимок экрана от 2022-05-28 15-26-31](https://user-images.githubusercontent.com/42237828/170811516-3812993d-af53-469c-9f58-fa14a66ac2bd.png)

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +            <b class="spec-range">800м</b>
с пробелом

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +      <h3 class="visually-hidden">Товары</h3>
Скорее, категории товаров

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +          <a href="#">Виртуальная реальность</a>
хватило бы одной ссылки на двоих)

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +    <h2 class="delivery-title" id="delivery">Доставка</h2>
зачем айдишник заголовку?

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +    <section class="services">
Опять же, список услуг и их описание - одна секция

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +  <span class="delivery-notice">Доставим редкий товар под заказ</span>
это скорее div - оно выглядит как блок, плюс там какие-то плюшки в нём есть (пока непонятные, т.к. макет не полный, кажется), возможно, будет кнопочка или ещё что-то.

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +      <h3 class="contacts-subtitle">Интернет-магазин «Девайс»</h3>
тут просто жирненький текст, не заголовок, он не озаглавливает раздел

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +      <a class="contacts-phone" href="tel:+78128121212">+7 (812) 812-12-12</a>
телефон в адрес не входит)

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +      <p class="contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
дополнительный p для текста в адресе не особо нужен, пока нет необходимости часть текста отдельно стилизовать

2022-05-28 06:32 UTC, Espanol-nikkol commented on catalog.html
> +               <address class="contacts-phone-number">
address - нужен только для физического адреса (город, улица, дом)

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +  <p class="warning">Это бесплатно</p>
а может есть тег, который лучше подходит к этому месту?

2022-05-28 06:32 UTC, Espanol-nikkol commented on index.html
> +  <img class="checked" src="#" alt="Это бесплатно">
Контентное изображение или декоративное?

2022-05-30 09:43 UTC, grechah commented on catalog.html
> +    <form class="search-form" action="https://echo.htmlacademy.ru/" method="get">
поправил.

2022-05-30 09:44 UTC, grechah commented on catalog.html
> +      <img class="login-icon" src="#" alt="Авторизация">
декоративная, поправил.

2022-05-30 09:44 UTC, grechah commented on catalog.html
> +      <a class="navigation-link" href="#">Коля Петухов</a>
кнопка, поправил.

2022-05-30 09:44 UTC, grechah commented on catalog.html
> +        <a href="#">Каталог товаров</a>
кнопка, поправил.

2022-05-30 09:50 UTC, grechah commented on catalog.html
> +    <input class="search-button" type="submit" name="submit" value="Найти">
поправил.

2022-05-30 09:52 UTC, grechah commented on catalog.html
> +          <a class="button" href="#delivery">Доставка</a>
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +    <h1 class="inner-header-title">Моноподы для селфи</h1>
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +    <header class="inner-header">
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +                <input class="control-input" type="range" min="0" max="10000" step="1000" value="5000">
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +            <img class="product-card-image" src="#" alt="#">
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +        <button class="button pagination-show-more" type="button">ПОКАЗАТЬ ЕЩЕ</button>
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +      <li class="services-item">Доставка</li>
поправил.

2022-05-30 09:53 UTC, grechah commented on catalog.html
> +      <p class="contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
поправил.

2022-05-30 09:56 UTC, grechah commented on catalog.html
> +          <span class="visually-hidden">Телеграм</span></a>
брал из примера барбершопа

<ul class="footer-social-list">
          <li class="footer-social-item">
            <a class="button" href="#">
              <span class="visually-hidden">Твиттер</span>
            </a>
          </li>
          <li class="footer-social-item">
            <a class="button" href="#">
              <span class="visually-hidden">ВКонтакте</span>
            </a>
          </li>
          <li class="footer-social-item">
            <a class="button" href="#">
              <span class="visually-hidden">Инстаграм</span>
            </a>
          </li>
        </ul>

2022-05-30 09:58 UTC, grechah commented on index.html
> +  <h1 class="main-title">01</h1>
поправил.

2022-05-30 09:58 UTC, grechah commented on index.html
> +      <ol class="slider-pagination">
не важен, поправил )

2022-05-30 09:58 UTC, grechah commented on index.html
> +  <section class="sliders">
поправил.

2022-05-30 09:58 UTC, grechah commented on index.html
> +            <b class="spec-range">800м</b>
поправил.

2022-05-30 09:58 UTC, grechah commented on index.html
> +      <h3 class="visually-hidden">Товары</h3>
поправил.

2022-05-30 09:58 UTC, grechah commented on index.html
> +          <a href="#">Виртуальная реальность</a>
поправил.

2022-05-30 09:59 UTC, grechah commented on index.html
> +    <h2 class="delivery-title" id="delivery">Доставка</h2>
я на него повесил якорь, только из-за этого.

2022-05-30 09:59 UTC, grechah commented on index.html
> +    <section class="services">
поправил.

2022-05-30 09:59 UTC, grechah commented on index.html
> +  <span class="delivery-notice">Доставим редкий товар под заказ</span>
поправил.

2022-05-30 10:00 UTC, grechah commented on index.html
> +      <h3 class="contacts-subtitle">Интернет-магазин «Девайс»</h3>
поправил.

2022-05-30 10:00 UTC, grechah commented on index.html
> +      <a class="contacts-phone" href="tel:+78128121212">+7 (812) 812-12-12</a>
поправил.

2022-05-30 10:00 UTC, grechah commented on index.html
> +      <p class="contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
поправил.

2022-05-30 10:00 UTC, grechah commented on catalog.html
> +               <address class="contacts-phone-number">
поправил.

2022-05-30 10:02 UTC, grechah commented on index.html
> +  <p class="warning">Это бесплатно</p>
может быть так ?)

2022-05-30 10:02 UTC, grechah commented on index.html
> +  <img class="checked" src="#" alt="Это бесплатно">
декоративное, поправил.

2022-06-01 01:39 UTC, Espanol-nikkol commented on catalog.html
> +          <button class="button" type="submit">Показать</button>
type="submit" - это дефолт, то, что стоит по умолчанию, можно не указывать

2022-06-01 01:39 UTC, Espanol-nikkol commented on catalog.html
> +        <button class="button pagination-show-more" type="button">ПОКАЗАТЬ ЕЩЕ</button>
Пишем мы орфографически верно. То есть каждое предложение с большой буквы и все остальное. Код - не место для игнорирования культуры языка) Хоть русского, хоть английского
Ну и тут ты поправил, а далее? Посмотри на код, там ещё есть аналогичные ошибки (про верхний регистр)

2022-06-01 01:40 UTC, Espanol-nikkol commented on catalog.html
> +      <li class="services-item">Доставка</li>
А у ссылок обязательно должен быть href. Хотя бы "#"

2022-06-01 01:52 UTC, grechah commented on catalog.html
> +          <button class="button" type="submit">Показать</button>
поправил.

2022-06-01 01:54 UTC, grechah commented on catalog.html
> +        <button class="button pagination-show-more" type="button">ПОКАЗАТЬ ЕЩЕ</button>
поправил.

2022-06-01 02:26 UTC, Espanol-nikkol commented on index.html
> +          <a href="#">Виртуальная реальность</a>
Поправил, а подписи потерял)


![Снимок экрана от 2022-06-01 12-12-51](https://user-images.githubusercontent.com/42237828/171315485-47a61a21-d897-4711-80a2-4619a97c55b8.png)

2022-06-01 02:31 UTC, Espanol-nikkol commented on index.html
> +    <section class="services">
В телеге обсудим

2022-06-01 02:58 UTC, Espanol-nikkol requested changes

2022-06-01 02:58 UTC, Espanol-nikkol commented on index.html
> +            alt="Изоюражение доставщика"
Опечаточка

2022-06-01 02:58 UTC, Espanol-nikkol commented on index.html
> +        <div class="delivery-description">
возвращаем обратно "р")

2022-06-01 02:58 UTC, Espanol-nikkol commented on index.html
> +        <img
лого академии должно быть в ссылке, а то при клике на картинку ничего не случится

2022-06-01 03:25 UTC, grechah commented on index.html
> +          <a href="#">Виртуальная реальность</a>
поправил.

2022-06-01 03:28 UTC, grechah commented on index.html
> +    <section class="services">
обсудили, три секции с h2

2022-06-01 03:29 UTC, grechah commented on index.html
> +            alt="Изоюражение доставщика"
поправил.

2022-06-01 03:30 UTC, grechah commented on index.html
> +        <div class="delivery-description">
вернул )

2022-06-01 03:30 UTC, grechah commented on index.html
> +        <img
поправил.

2022-06-01 04:21 UTC, Espanol-nikkol approved these changes

2022-06-01 04:21 UTC, merged