Базовая стилизация всех страниц
htmlacademy-htmlcss/2062283-device-34 pull request #4
Opened 2022-06-06 13:34 UTC by grechah

---
:mortar_board: [Базовая стилизация всех страниц](https://up.htmlacademy.ru/htmlcss/34/user/2062283/tasks/6)

:boom: https://htmlacademy-htmlcss.github.io/2062283-device-34/4/

2022-06-06 14:33 UTC, Espanol-nikkol requested changes

2022-06-06 14:33 UTC, Espanol-nikkol commented on styles/styles.css
> +    background-color: #ffffff;
а дефолтный цвет какой?

2022-06-06 14:33 UTC, Espanol-nikkol commented on styles/styles.css
> +    font-family: inherit;
мы можем написать использовать селектор * - любой тег. Написать его в самом верху файла стилей, после шрифтов. И ему сказать, какие у нас должен быть стили, который повторяются почти для всех элементов

2022-06-06 14:33 UTC, Espanol-nikkol commented on styles/styles.css
> +    height: 100px;
высота регулируется контентом, не зажимай её

2022-06-06 14:35 UTC, Espanol-nikkol requested changes

2022-06-06 14:35 UTC, Espanol-nikkol commented on styles/styles.css
> +    background-color: #F0F0F0;
Давай все hex цвета либо капсом, либо маленькими
Единообразие в коде - спасёт мир

2022-06-06 14:47 UTC, grechah commented on styles/styles.css
> +    height: 100px;
поправил.

2022-06-06 14:48 UTC, grechah commented on styles/styles.css
> +    background-color: #F0F0F0;
поправил.

2022-06-06 14:48 UTC, grechah commented on styles/styles.css
> +    font-family: inherit;
обсудили в тг.

2022-06-07 04:59 UTC, grechah commented on styles/styles.css
> +    background-color: #ffffff;
поправил )

2022-06-07 14:32 UTC, Espanol-nikkol requested changes

2022-06-07 14:32 UTC, Espanol-nikkol commented on styles/styles.css
> +    color: #ffffff;
а зачем? его же не видно теперь

2022-06-07 14:32 UTC, Espanol-nikkol commented on styles/styles.css
> +    ;
потеряшка

2022-06-07 14:32 UTC, Espanol-nikkol commented on styles/styles.css
> +    color: #ffffff;
понял, один класс у телефона в "контакты" и в подвале. А надо разные, пусть и очень похожие, чтобы цвета разделить

2022-06-08 07:45 UTC, grechah commented on styles/styles.css
> +    color: #ffffff;
поправил.

2022-06-08 07:45 UTC, grechah commented on styles/styles.css
> +    ;
поправил.

2022-06-08 10:33 UTC, Espanol-nikkol approved these changes

2022-06-09 13:58 UTC, Espanol-nikkol requested changes

2022-06-09 13:58 UTC, Espanol-nikkol commented on styles/styles.css
> +    height: 100%;
а без этого он не всю высоту занимает?

2022-06-09 13:58 UTC, Espanol-nikkol commented on styles/styles.css
> +    min-height: 100%;
обсудили необходимость этого в телеге

2022-06-09 13:58 UTC, Espanol-nikkol commented on styles/styles.css
> +    height: 100%;
Или это тоже из скринкаста?

2022-06-09 13:58 UTC, Espanol-nikkol commented on catalog.html
> +          </li>
лишний закрывающий тег

2022-06-13 04:14 UTC, Espanol-nikkol approved these changes

2022-06-13 04:14 UTC, merged